'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import BannerSlider from "@/components/BannerSlider"
import AboutBanner from "@/components/AboutBanner"
import ProgramAnimation from '@/components/ProgramAnimation'
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import TeamSlider from '@/components/TeamSlider'

const AboutPage = () => {
    const sliderRef = useRef(null);

    const handlePrev = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slidePrev();
    }, []);

    const handleNext = useCallback(() => {
        if (!sliderRef.current) return;
        sliderRef.current.swiper.slideNext();
    }, []);
 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutBanner />
      <section className='side-img-sec sec'>
        <img class="vec-grad" src="/assets/images/grad.svg" />
        <div className="container">
           <div className="row items-center">
             <div className="col-md-6">
               <div className='side-img'>
               
               <img src='/assets/images/side-img-1.png' />
               </div>
             </div>
             <div className="col-md-6">
               <div className='side-con'>
               <h3 className="sec-head">
               Our Ethos
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />At Stance Health, our mission is to provide high-quality care to all who aspire to have an active life. We are dedicated to redefining healthcare standards by fostering innovation in technology and using it to create patient-centered excellence in MSK care.</li>
                <li><img src="/assets/images/tick.svg" />We strive to restore function, reduce pain, and promote overall well-being by delivering exceptional and innovative physiotherapy and strengthening programs.</li>
              </ul>
               </div>
             </div>
           </div>
        </div>
      </section>
      <section className="sec test-sec">
            <div className="container">
                <div className="row">
                    <div className="col-12 text-center">
                        <h3 className="sec-head">
                        Who <span>helps you</span> take a Stance?
                        </h3>
                        <p className="para">
                        Stance is built on patient-centered care, supported by a proficient physiotherapy team that guides you through your rehab journey, addressing every aspect of your wellness. Our highly expert team comprises Physiotherapists, Strength and Conditioning Coaches, Sports Massage Therapists, and Medical and Sports Consultants.
                        </p>
                    </div>
                    <div className="col-12">
                        <div className="team-slider">
                            <Swiper
                            ref={sliderRef}
                                scrollbar={{
                                    hide: false,
                                    draggable: true,
                                }}
                                className="team-swiper"
                                modules={[Autoplay,Scrollbar]}
                                autoplay={{
                                    delay: 3000,
                                    disableOnInteraction: false,
                                }}
                                slidesPerView={4}
                                spaceBetween={0}
                                breakpoints={{
                                    0: {
                                        slidesPerView: 1.3,
                                        spaceBetween: 20,
                                    },
                                    640: {
                                        slidesPerView: 2,
                                        spaceBetween: 20,
                                    },
                                    768: {
                                        slidesPerView: 3,
                                        spaceBetween: 30,
                                    },
                                    1024: {
                                        slidesPerView: 4,
                                        spaceBetween: 40,
                                    },
                                }}
                                // onBeforeInit={(swiper) => {
                                // }}
                                // ref={sliderRef}
                            >
                                {
                                    [...Array(5)].map((item,index)=>{
                                        return(
                                            <SwiperSlide key={index}>
                                                <div className="team-card">
                                                    <Image src="/assets/images/team.jpg" width={1500} height={1500} alt="" />
                                                    <div className="con">
                                                        <div className="tp">
                                                            <h3>
                                                            Riya Choudry
                                                            </h3>
                                                            <h4>Team Lead, Automation</h4>
                                                        </div>
                                                        <p className="para">
                                                        Lorem Ipsum is simply dummy text of the printing and  typesetting industry. Lorem Ipsum has been the industry's standard dummy  text ever since the 1500s
                                                        </p>
                                                    </div>
                                                </div>
                                            </SwiperSlide>
                                        )
                                    })
                                }
                            </Swiper>
                            <div className="tech-nav">
                                <button className='tech-prev' onClick={handlePrev}>
                                    <Image src="/assets/images/prev.svg" width={50} height={50} />
                                </button>
                                <button className='tech-next' onClick={handleNext}>
                                    <Image src="/assets/images/next.svg" width={50} height={50} />
                                </button>
                            </div>
                        </div>

                            
                    </div>
                </div>
            </div>
        </section>

    </>
  )
}

export default AboutPage