'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import BlogInnerBanner from "@/components/BlogInnerBanner"
import ReviewForm from '@/components/ReviewForm';
import Testimonial from "@/components/TestimonialSlider"
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";
import Button from 'react-bootstrap/Button';
import Col from 'react-bootstrap/Col';
import Form from 'react-bootstrap/Form';
import Row from 'react-bootstrap/Row';

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import TeamSlider from '@/components/TeamSlider'

const BlogInnerPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogInnerBanner />
      <section className='sec'>
         <div className='container'>
           <div className='row'>
             <div className='col-md-8'>
               <div className='auth-meta'>
                 <div className='auth-img'>
                   <img src="/assets/images/auth.svg" />
                 </div>
                 <div className='auth-con'>
                   <h3>Andrew Jonson</h3>
                   <span>Posted on 27th January 2022</span>
                 </div>
               </div>
               <div className='blog-title'>
                  <h2 className='sec-head'>Step-by-step guide to choosing great font pairs</h2>
               </div>
               <div className='blog-content'>
                  <div className='blog-content-block'>
                     <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</h3>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                  </div>
                  <div className='blog-content-block'>
                     <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</h3>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                     <ul>
                        <li>Lorem ipsum dolor sit amet</li>
                        <li>Non blandit massa enim nec scelerisque</li>
                        <li>Neque egestas congue quisque egestas</li>
                     </ul>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                  </div>
                  <div className='blog-content-block'>
                     <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</h3>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                  </div>
                  <div className='blog-content-block'>
                     <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</h3>
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non.</p>
                  </div>
               </div>
             </div>
             <div className='col-md-4'>
                <div className='blog-inner-sidebar'>
                <div className='link-box categroy-box'>
                <h3 className='sec-head dark xs center'>Categories</h3>
                <a href='#grpfaq1'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
                <a href='#grpfaq2'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
                <a href='#grpfaq3'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
                <a href='#grpfaq4'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
                <a href='#grpfaq5'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
                <a href='#grpfaq6'>Heading One <img src="/assets/images/angle-right.svg" /></a>
                <span className='line'></span>
              </div>
              <div className='side-reviewbox'>
              <h3 className='sec-head dark xs center'>Reviews</h3>
              <div className='side-review-list'>
              <div className='side-review'>
                 <img src="/assets/images/star.svg" />
                 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. </p>
                 <div className='reviewer-con'>
                    <h3>Andrew Jonson</h3>
                    <span>Posted on 27th January 2022</span>
                 </div>
              </div>
              <div className='side-review-line'></div>
              <div className='side-review'>
                 <img src="/assets/images/star.svg" />
                 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. </p>
                 <div className='reviewer-con'>
                    <h3>Andrew Jonson</h3>
                    <span>Posted on 27th January 2022</span>
                 </div>
              </div>
              </div>
              
              </div>
                </div>
             
             </div>
           </div>
         </div>
      </section>
      <section className='sec'>
        <div className='container'>
          <div className='row'>
            <div className='col-md-12'>
               <h2 className='sec-head xs'>Write Your Review</h2>
               <div className='review-form'>
                 <ReviewForm />
               </div>
            </div>
          </div>
        </div>
      </section>
      <section className='sec'>
        <div className='container'>
          <div className='row'>
            <div className='col-md-6'>
              <h2 className='sec-head'>What i Read Next</h2>
            </div>
          </div>
          <div className='row'>
          <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default BlogInnerPage