'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import BlogBanner from "@/components/BlogBanner"
import Testimonial from "@/components/TestimonialSlider"
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import TeamSlider from '@/components/TeamSlider'

const BlogPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogBanner />
      <section className='sec tab-sec'>
        <div className='container'>
          <div className='row'>
            <div className='col-md-12'>
              <h2 className='sec-head center'>How we do it?</h2>
              <div className='cr-tabs'>
              <ul className="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <img className='tab-line' src='/assets/images/tab-line.svg' />
  <li className="nav-item" role="presentation">
    <button className="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
      <div className='tab-grp'>
      <div className='on-ac-img'>
          <img className='ac-img' src="/assets/images/tab-1-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-1.svg" />
         </div>
         </div>
         <h3>Technology<br />
Assessment</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
    <div className='tab-grp'>
    <div className='on-ac-img'>
    <img className='ac-img' src="/assets/images/tab-2-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-2.svg" />
         </div>
         </div>
         <h3>Physiotherapy</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
    <div className='tab-grp'>
    <div className='on-ac-img'>
    <img className='ac-img' src="/assets/images/tab-3-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-3.svg" />
         </div>
         </div>
         <h3>Strength &<br />
Conditioning</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-4-tab" data-bs-toggle="pill" data-bs-target="#pills-4" type="button" role="tab" aria-controls="pills-4" aria-selected="false">
    <div className='tab-grp'>
         <div className='on-ac-img'>
         <img className='ac-img' src="/assets/images/tab-4-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-4.svg" />
         </div>
         </div>
         
         <h3>At-Home<br />
Technology</h3>
      </div>
    </button>
  </li>
</ul>
<div className="tab-content" id="pills-tabContent">
  <div className="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
    <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-4" role="tabpanel" aria-labelledby="pills-4 -tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row'>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
        <div className='col-md-4'>
           <div className='blog-div'>
             <div className='blog-img'>
               <img src="/assets/images/b-1.png" />
             </div>
             <div className='blog-div-meta'>
               <div className='author-div'><p>By <a>John Doe</a></p></div>
               |
               <div className='date-div'><p>Aug 23, 2021</p></div>
             </div>
             <div className='blog-con'>
               <h3>A UX Case Study Creating a Studious Environment for Students: </h3>
               <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
             </div>
           </div>
        </div>
      </div>
    </div>
  </div>
</div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Testimonial />
    </>
  )
}

export default BlogPage