'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import BookNowBanner from "@/components/BookNowBanner"
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import TeamSlider from '@/components/TeamSlider'

const BookNowPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookNowBanner />
      <section className='sec booknow-sec'>
      <Image src={'/assets/images/curve.svg'} alt="" width={1920} height={1080} />
        <div className='container'>
          <div className='row items-center'>
            <div className='col-md-6'>
              <div className='side-con'>
                <h3 className='sec-head dark'>Book an appointment with us</h3>
                <p className='para dark'>The whole session of running form analysis takes ~30 minutes<br />
The analysis will cost ₹ 3500<br />
Details will be sent to you about prerequisites, once your appointment is confirmed<br />
Please see FAQ for more details</p>
              <h3 className='small-head dark'>Living in Whitefield area? Or looking for a weekday appointment?</h3>
              </div>
            </div>
            <div className='col-md-6'>
              <div className='side-img'>
                <img src='/assets/images/calendly.png' />
              </div>
            </div>
          </div>
        </div>
      </section>

    </>
  )
}

export default BookNowPage