'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import InjuryManagementBanner from "@/components/InjuryManagementBanner"
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import RunningBottom from '@/components/RunningBottom'

const InjuryManagementPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InjuryManagementBanner />
      <section className='sec running-program-sec'>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-md-12'>
               <div className='center-con center'>
                  <h3 className='sec-head'>Why Join <span>our Running</span> Programmes?</h3>
                  <p className='para'>Our extensive running program is designed for everyone, backed by high end technology-based measurements.<br />  Our approach focuses on improving mobility, stability, agility, balance, coordination, strength, speed, and power,<br /> tailored to individual needs.</p>
               </div>
                  
            </div>
          </div>
        </div>
        <div className='running-program-row running-program-row-1'>
            <img className='r-line' src='/assets/images/r-line-1.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid three'>
                 <div className='running-program-div'>
                    <img src="/assets/images/r-1.svg" />
                    <h3>Prepare for<br /> your upcoming<br /> marathons</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/r-2.svg" />
                    <h3>Reduced risk<br /> of running<br /> injuries</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/r-3.svg" />
                    <h3>Expert Management<br /> of running-induced<br /> injuries</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row'>
            <img className='r-line r-line-2' src='/assets/images/r-line-2.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid two'>
                 <div className='running-program-div'>
                    <img src="/assets/images/r-4.svg" />
                    <h3>Successful<br /> return to<br /> running</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/r-5.svg" />
                    <h3>Maximise<br /> efficiency and<br /> performance</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>
          <RunningBottom />

      <section className='running-cta sec'>
        <div className='container'>
         <img className='cta-bg' src="/assets/images/im-cta.svg" />
          <div className='row items-center'>
            <div className='col-md-8'>
              <div className='cta-side'>
                <h3 className='sec-head sm'>Ready to take your running to the next level?</h3>
                <p className='para'>Book now & let our proven running programs guide you<br /> towards achieving your goals with confidence.</p>
              </div>
            </div>
            <div className='col-md-3 offset-md-1 right'>
            <Link href="/" className='main-btn big'>
                                <span>Book Now</span>
                            </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default InjuryManagementPage