'use client'
import {useState, useEffect, useLayoutEffect, useRef, useCallback} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import PhilosophyBanner from "@/components/PhilosophyBanner"
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Autoplay } from 'swiper/modules';
import { Navigation, Scrollbar } from 'swiper/modules';
import "swiper/css";

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import TeamSlider from '@/components/TeamSlider'

const PhilosophyPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PhilosophyBanner />
      <section className='sec tab-sec'>
        <div className='container'>
          <div className='row'>
            <div className='col-md-12'>
              <h2 className='sec-head center'>How we do it?</h2>
              <div className='cr-tabs'>
              <ul className="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <img className='tab-line' src='/assets/images/tab-line.svg' />
  <li className="nav-item" role="presentation">
    <button className="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
      <div className='tab-grp'>
      <div className='on-ac-img'>
          <img className='ac-img' src="/assets/images/tab-1-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-1.svg" />
         </div>
         </div>
         <h3>Technology<br />
Assessment</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
    <div className='tab-grp'>
    <div className='on-ac-img'>
    <img className='ac-img' src="/assets/images/tab-2-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-2.svg" />
         </div>
         </div>
         <h3>Physiotherapy</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
    <div className='tab-grp'>
    <div className='on-ac-img'>
    <img className='ac-img' src="/assets/images/tab-3-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-3.svg" />
         </div>
         </div>
         <h3>Strength &<br />
Conditioning</h3>
      </div>
    </button>
  </li>
  <li className="nav-item" role="presentation">
    <button className="nav-link" id="pills-4-tab" data-bs-toggle="pill" data-bs-target="#pills-4" type="button" role="tab" aria-controls="pills-4" aria-selected="false">
    <div className='tab-grp'>
         <div className='on-ac-img'>
         <img className='ac-img' src="/assets/images/tab-4-hov.png" />
         <div className='icon-grp'>
           <img src="/assets/images/tab-4.svg" />
         </div>
         </div>
         
         <h3>At-Home<br />
Technology</h3>
      </div>
    </button>
  </li>
</ul>
<div className="tab-content" id="pills-tabContent">
  <div className="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
    <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-6'>
           <div className='side-img'>
             <img src='/assets/images/tech-asses.svg' />
           </div>
        </div>
        <div className='col-md-6'>
        <div className='side-con'>
               <h3 className="sec-head">
               Technology Focussed Assessments
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />We believe in measuring what matters! Our technology-focused assessment monitors key aspects of your condition, providing valuable insights to contextualize your progress.</li>
                <li><img src="/assets/images/tick.svg" />Stance Health offers a deep understanding of data inputs using state of the art tools across Running, Muscle Strength, Range of Motion, Endurance, and Progress, enabling a comprehensive evaluation of your health journey.</li>
              </ul>
               </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-6'>
           <div className='side-img'>
             <img src='/assets/images/side-img-4.png' />
           </div>
        </div>
        <div className='col-md-6'>
        <div className='side-con'>
               <h3 className="sec-head">
               Physiotherapy:
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />Our physiotherapy services include a detailed evaluation using cutting-edge sport science technology, catering to individuals from professional athletes to grassroots participants.</li>
                <li><img src="/assets/images/tick.svg" />MSK assessment: Conduct an audit on muscles and joints to identify at-risk and potential risk conditions.</li>
                <li><img src="/assets/images/tick.svg" />Injury management: Addressing injuries through manual therapy techniques for effective pain management.</li>
                <li><img src="/assets/images/tick.svg" />Injury prevention: Offering a progressive and customized set of active exercises tailored to each individual's needs</li>
              </ul>
               </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-6'>
           <div className='side-img'>
             <img src='/assets/images/sc.svg' />
           </div>
        </div>
        <div className='col-md-6'>
        <div className='side-con'>
               <h3 className="sec-head">
               Strength and Conditioning :
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />Our S&C programs help individuals reach outcomes based on their goals. While goals can be across functional activities or returning to sport, strength, and conditioning is a crucial element that helps ensure better management of MSK issues.</li>
                <li><img src="/assets/images/tick.svg" />Seamless Everyday Routines: Breeze through daily tasks effortlessly. Our functional strength and conditioning programs ensure you are ready to fulfill everyday activities effortlessly.</li>
                <li><img src="/assets/images/tick.svg" />Elevated Sporting Excellence: Unlock your full potential in sports with training designed for athletes across various sporting disciplines.  We ensure this by accurately measuring progress using advanced technologies and modifying regimens basis your progress.</li>
              </ul>
               </div>
        </div>
      </div>
    </div>
  </div>
  <div className="tab-pane fade" id="pills-4" role="tabpanel" aria-labelledby="pills-4 -tab" tabindex="0">
  <div className='the-tab-content'>
      <div className='row items-center'>
        <div className='col-md-6'>
           <div className='side-img'>
             <img src='/assets/images/aht.svg' />
           </div>
        </div>
        <div className='col-md-6'>
        <div className='side-con'>
               <h3 className="sec-head">
               At- Home Sessions:
              </h3>
              <ul>
                <li><img src="/assets/images/tick.svg" />With at-home monitoring technology using Healthflex, we aim to deliver high-tech and efficient at-home sessions and assessments. We ensure you don't always need to visit the clinic and can still continue your rehab journey without leaving the comfort of your home. </li>
                <li><img src="/assets/images/tick.svg" />We use AI-Driven Motion Sensors to track movements and give real-time feedback so that you always supervised throughout you rehab</li>
                <li><img src="/assets/images/tick.svg" />Movement data is used to ensure we keep track of progress and tailor programs  basis your recovery</li>
              </ul>
               </div>
        </div>
      </div>
    </div>
  </div>
</div>
              </div>
            </div>
          </div>
        </div>
      </section>
       <section className='sec features-sec'>
          <div className='container'>
             <div className='row'>
                <div className='col-md-12'>
                <div className='center-con center'>
                  <h3 className='sec-head'>What makes us <span>stand</span> apart ?</h3>
                  <p className='para'>So, what makes Stance different from other clinics?</p>
               </div>
                </div>
             </div>
             <div className='row feature-row'>
               <div className='col-md-6'>
                 <div className='featue-div'>
                   <div className='feature-div-img'>
                     <img src="assets/images/f-1.png" />
                   </div>
                   <div className='feature-div-con'>
                     <h3>Empowering Patient Education</h3>
                     <p>At Stance, we prioritize patient education as a cornerstone of our approach. We believe in equipping our patients with comprehensive knowledge about their condition and empowering them with preventive strategies to avoid future injuries.</p>
                   </div>
                 </div>
               </div>
               <div className='col-md-6'>
                 <div className='featue-div'>
                   
                   <div className='feature-div-con'>
                     <h3>Objective Technology Based Excellence</h3>
                     <p>At Stance, we uphold an evidence-based approach that leverages objective measuring systemsand technology. This allows us to provide robust insights, facilitating baselining, benchmarking, and continuous monitoring as part of our data-driven methodology.</p>
                   </div>
                   <div className='feature-div-img'>
                     <img src="assets/images/f-2.png" />
                   </div>
                 </div>
               </div>
               <div className='col-md-6'>
                 <div className='featue-div'>
                   <div className='feature-div-img'>
                     <img src="assets/images/f-3.png" />
                   </div>
                   <div className='feature-div-con'>
                     <h3>Expert Therapists</h3>
                     <p>Stance Health boasts a team of distinguished therapists who excel not only in their extensive training but also in their rich experience across diverse conditions. They are dedicated to remaining at the forefront of advancements, continuously updating their skills with the latest techniques and treatments.</p>
                   </div>
                 </div>
               </div>
               <div className='col-md-6'>
                 <div className='featue-div'>
                   
                   <div className='feature-div-con'>
                     <h3>Multi-Disciplinar</h3>
                     <p> We combine elements of Sports Orthopaedics, Physical Therapy, and Strength & Conditioning, to ensure we help you recover faster across all phases of your journey. Ranging from Post-surgical, Chronic to Performance Improvement our approach ensures we are with you every step of the way.</p>
                   </div>
                   <div className='feature-div-img'>
                     <img src="assets/images/f-4.png" />
                   </div>
                 </div>
               </div>
             </div>
          </div>
       </section>
    </>
  )
}

export default PhilosophyPage