'use client'
import {useState, useEffect, useLayoutEffect} from 'react'
import Image from "next/image"
import Link from "next/link"
import Head from "next/head"
import BannerSlider from "@/components/BannerSlider"
import ProgramBanner from "@/components/ProgramBanner"
import ProgramAnimation from '@/components/ProgramAnimation'

import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useGSAP } from '@gsap/react';

const ProgramPage = () => {
  useEffect(() => {
    const items = document.querySelectorAll(".item");
    const drums = document.querySelectorAll(".ball");
    items.forEach((item, index) => {
      let angle = (index + 1) * 72;
      setInterval(function () {
        item.style.transform = `translateX(50%) rotate(${angle}deg)`;
        drums.forEach((drum) => {
          drum.style.transform = `rotate(${angle / 7}deg)`;
        });
        angle = angle + 10;
      }, 500);
    });
  }, []);
  const [open, setOpen] = useState(1)
  useLayoutEffect(() => {
    let ctx = gsap.context(() => {
          var tl = gsap.timeline({
          })
          tl.to('.he-col.active .he-cards', {
            position: 'relative',
          })
          tl.to('.he-col.active .he-cards', {
            opacity: 1,
            // y: '0px'
          }, "-=0.4")
        //   lottieInstance.current = lottieAnimation?.getLottie();
    });
    return () => {
      ctx.revert();
    };
  }, [open]);
 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProgramBanner />
      <section className="he-sec">
        <div className="he-cols">
          <div className={`he-col ${open == 1 && 'active'}`} onClick={(e)=>setOpen(1)}>
            <Image src="/assets/images/reasses.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>REASSESS</h3>
              <p className="para">
              To ensure we understand the root cause
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>Technology</h3>
                  <ul>
                    <li>
                    Objective Assessments using State-of-the-art Tools
                    </li>
                    <li>
                    300+ Tests Based on conditions and symptoms
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>Clinical</h3>
                  <ul>
                    <li>
                    Evidence Backed Manual Techniques with therapists
                    </li>
                    <li>
                    Triaging using Technology Data and Manual Assessments
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className={`he-col ${open == 2 && 'active'}`} onClick={(e)=>setOpen(2)}>
            <Image src="/assets/images/restore.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>RESTORE</h3>
              <p className="para">
              Creating a path to get you back to your old self.
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>Physical Therapy</h3>
                  <ul>
                    <li>
                    Pain relief using evidence backed procedures
                    </li>
                    <li>
                    Assisted movements for maximising function
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>S&C</h3>
                  <ul>
                    <li>
                    Goal specific transition to Muscle Strengthening
                    </li>
                    <li>
                    Conditioning to prevent relapse
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className={`he-col ${open == 3 && 'active'}`} onClick={(e)=>setOpen(3)}>
            <Image src="/assets/images/reignite.svg" alt="" width={1200} height={1200} />
            <div className="con">
              <h3>REIGNITE</h3>
              <p className="para">
              Building you to reach your Goals
              </p>
              <div className="he-cards">
                <div className="he-card">
                  <div className="ic">
                    <span>1</span>
                  </div>
                  <h3>S&C</h3>
                  <ul>
                    <li>
                    Maximise performance with experts
                    </li>
                    <li>
                    Data backed assessments to monitor progress
                    </li>
                  </ul>
                </div>
                <div className="he-card">
                  <div className="ic">
                    <span>2</span>
                  </div>
                  <h3>At-Home</h3>
                  <ul>
                    <li>
                    Clinical Supervision at Home using Technology
                    </li>
                    <li>
                    Data Driven reports used for Doctor check-ins
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="sec pb-0 circ-sec">
        <div className="container">
          <div className="row">
            <div className="col-12">
              
            </div>
          </div>
          <div className="row justify-content-center">
            <div className="col-lg-6 col-12">
              {/* <ProgramAnimation /> */}
              {/* <div className="circ-img">
              <Image src="/assets/images/circ.png" alt='' width={1920} height={1080} />
              </div> */}
<div id="container">
  <div id="image-container">
    <img src="/assets/images/ava.png" alt="" className="image" />
  </div>
  <a href="/running" className="item">
    <div className="ball ball1"></div>
  </a>
  <a href='/performance-training' className="item">
    <div className="ball ball2"></div>
  </a>
  <a href="/injury-management" className="item">
    <div className="ball ball3"></div>
  </a>
  <a href='/surgical-rehab' className="item">
    <div className="ball ball4"></div>
  </a>
  <a href='/back-to-sports' className="item">
    <div className="ball ball5"></div>
  </a>
</div>

            </div>
            <div className='col-lg-5 offset-lg-1 col-12'>
               <div className='program-side-anim'>
                  <h2 className='sec-head'>Our Program</h2>
                  <div className='programs-list'>
                     <div className='program-div'>
                        <div className='program-div-img'>
                           <a href="/running"><img src='/assets/images/circ-1.png' /></a>
                        </div>
                        <div className='program-div-con'>
                        <a href="/running"><h3>Running</h3></a>
                          <p>Running improves heart and lung function, boosts endurance, and enhances overall fitness.</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <a href="/surgical-rehab"><img src='/assets/images/circ-4.png' /></a>
                        </div>
                        <div className='program-div-con'>
                        <a href="/surgical-rehab"><h3>Surgical rehab</h3></a>
                          <p>Regular running strengthens muscles, bones, and joints, improving posture, balance, and flexibility.</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <a href="/back-to-sports"><img src='/assets/images/circ-5.png' /></a>
                        </div>
                        <div className='program-div-con'>
                        <a href="/back-to-sports"><h3>Back to play</h3></a>
                          <p>Running increases metabolism, aiding weight management and boosting energy levels.</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <a href="/performance-training"><img src='/assets/images/circ-2.png' /></a>
                        </div>
                        <div className='program-div-con'>
                        <a href="/performance-training"><h3>Physical fitness</h3></a>
                          <p>Running reduces stress, boosts mood, sharpens cognitive function, and promotes a positive mindset.</p>
                        </div>
                     </div>
                     <div className='program-div'>
                        <div className='program-div-img'>
                        <a href="/injury-management"><img src='/assets/images/circ-3.png' /></a>
                        </div>
                        <div className='program-div-con'>
                        <a href="/injury-management"><h3>Injury management</h3></a>
                          <p>Incorporating running into your routine fosters discipline, goal-setting, and personal growth for a fulfilling and active life.</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default ProgramPage